/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigTab: typeof import('./src/components/ConfigTab.vue')['default']
    DownloadTab: typeof import('./src/components/DownloadTab.vue')['default']
    NodesTab: typeof import('./src/components/NodesTab.vue')['default']
    SettingTab: typeof import('./src/components/SettingTab.vue')['default']
  }
}
