#!/bin/bash

### This script is called after the user uninstalls the application.
set -e

source /var/apps/${TRIM_APPNAME}/cmd/common.sh

if [[ "${wizard_data_action}" == "keep"]]; then
    log_msg "卸载时保留数据"
    exit 0
else
    run_cmd "rm -f ${CFG_FILE}"
    run_cmd "rm -f ${INIT_FILE}"
    run_cmd "rm -f ${GITHUB_PROXY_URL_CFG_FILE}"
fi

exit 0